### ISSUE TITLE
ClientFactoryInterface doesn't exist for a product page

### ISSUE THREAD

**Issue by moreauSmile** [Smile-SA/magento2-module-elasticsuite-targetrule#10]
In a Percolator Class we use again a ClientFactoryInterface class be she's not exist in Core ElasticSuite Module.

Moreover, they missing function get an percolate for Class Smile\ElasticsuiteCore\Client\Client

**Comment by romainruaud** [comment]
This might be due to some core refactoring on latest 2.5.0 elasticsuite release.

Are you using this version ?

**Comment by afoucret** [comment]
Hi having the percolation API have been completly rewritten in ES 5.x in a way that is not backward compatible. at all

The 2.5.0 version of ElasticSuite aims to bring ES 5.x.
In a next version we will integrate the percolation directly in the ElasticSuite core module but we can do this only when we drop the support for ES 2.x.

I fear this module will remain incompatible with ElasticSuite >= 2.5.x for a while.

BR

**Comment by romainruaud** [comment]
Compatibility with Magento 2.3.x fixed by latest release.
