### ISSUE TITLE
Not compatible with Elasticsuite 2.9

### ISSUE THREAD

**Issue by Coosos** [Smile-SA/magento2-module-elasticsuite-targetrule#11]
Hi,

This module is not compatible with elasticsuite 2.9 because it uses the `datasources` tag in elasticsuite_indices.xml and this MR: https://github.com/Smile-SA/elasticsuite/pull/1401/ removes this option.

```
Verify the XML and try again. {"exception":"[object] (Magento\\Framework\\Exception\\LocalizedException(code: 0): The XML in file \"/var/www/magento235-ee/vendor/smile/module-elasticsuite-targetrule/etc/elasticsuite_indices.xml\" is invalid:
Element 'datasources': This element is not expected. Expected is ( mapping ).
Line: 24

Verify the XML and try again. at /var/www/magento235-ee/vendor/magento/framework/Config/Reader/Filesystem.php:156)"} []
```

**Comment by rbayet** [comment]
Hello @Coosos,

Release 1.4.0 addressed that specific issue but will be superseded by incoming 1.4.1 which contains additional fixes (see https://github.com/Smile-SA/magento2-module-elasticsuite-targetrule/pull/13)

Regards,

**Comment by rbayet** [comment]
Hello @Coosos,

Release [1.4.1](https://github.com/Smile-SA/magento2-module-elasticsuite-targetrule/releases/tag/1.4.1) is now available.

Regards,
