### ISSUE TITLE
Unable to reindex catalogsearch_fulltext

### ISSUE THREAD

**Issue by aaronware** [Smile-SA/magento2-module-elasticsuite-targetrule#5]
## Relevant information
Magento Version 2.1.7
PHP Version 7.0.17

## Enabled Modules
Smile_ElasticsuiteCore 2.3.0
Smile_ElasticsuiteCatalog
Smile_ElasticsuiteCatalogRule
Smile_ElasticsuiteCatalogOptimizer
Smile_ElasticsuiteSwatches
Smile_ElasticsuiteVirtualCategory
Smile_ElasticsuiteThesaurus
Smile_ElasticsuiteTracker
Smile_ElasticsuiteTargetRule 1.1

## How to reproduce

Follow install instructions. Ending with the following command.

```
$ bin/magento indexer:reindex catalogsearch_fulltext
PHP Fatal error:  Uncaught Error: Call to a member function getStoreGroupId() on null in /html/vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/Rule.php:346
Stack trace:
#0 /html/vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/Rule.php(201): Smile\ElasticsuiteVirtualCategory\Model\Rule->getRootCategoryId(NULL)
#1 /html/vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/Rule.php(249): Smile\ElasticsuiteVirtualCategory\Model\Rule->getVirtualRootCategory(Object(Magento\Catalog\Model\Category\Interceptor))
#2 /html/vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/Rule.php(138): Smile\ElasticsuiteVirtualCategory\Model\Rule->getVirtualCategoryQuery(Object(Magento\Catalog\Model\Category\Interceptor), Array)
#3 /html/vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/Rule.php(2 in /html/vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/Rule.php on line 346
```
If Smile_ElasticsuiteTargetRule is disabled. Reindexing of `catalogsearch_fulltext` is possible

**Comment by aaronware** [comment]
This may in actuality be a bug in Smile_Elasticsuite but I thought it was best to add the issue here first as it didn't occur until Smile_ElasticsuiteTargetRule install instructions were followed

**Comment by romainruaud** [comment]
Hello @aaronware ,

are you running a multi store instance ? If yes, could you give more details about how it's built ? Especially for the categories, how many "root" do you have, and which store are they attached to.

Best regards,

**Comment by aaronware** [comment]
Hi @romainruaud.

Yes it is a multistore instance. There are a large amount of websites (currently 8) with mostly a 1 - 1 -1 for Website, Store, Storeview. There is one website however that has 13 stores and each with their own individual storeviews.

Longer term that is going to change to 6 websites with potentially different stores and store views. I could move the stores around now if needed (if that is causing an issue)

There are currently 7 root categories. 1 Default root category and 6 website specific roots.

A few of the stores are referencing the default root some are referencing their website specific root

Additional / maybe helpful information.

This is a migration from m1 to m2 so I am not sure if that will be helpful or if it matters
