### ISSUE TITLE
Magento 2.2 Compilation

### ISSUE THREAD

**Issue by EliasKotlyar** [Smile-SA/magento2-module-elasticsuite-targetrule#7]
### Preconditions
Have a working Magento 2.2 Installation . 
Magento Version : CE and EE
ElasticSuite Version : 2.3 / 2.4 with TargetRule

Environment : Developer / Production

Third party modules : No

### Steps to reproduce
Install into Magento 2.2
Start compiling process using /bin/magento setup:di:compile

### Expected result
You can compile your di
                                                               

### Actual result
	Smile\ElasticsuiteTargetRule\Plugin\Indexer\TargetRule\Product\RuleProxies code generation... 1/7 [====>-----------------------]  14% 2 secs 70.0 MiB
Repositories code generation... 1/7 [====>-----------------------]  14% 2 secs 70.0 MiB
Repositories code generation... 2/7 [========>-------------------]  28% 48 secs 246.0 MiB
Service data attributes generation... 2/7 [========>-------------------]  28% 48 secs 246.0 MiB
Service data attributes generation... 3/7 [============>---------------]  42% 48 secs 246.0 MiB
Application code generator... 3/7 [============>---------------]  42% 48 secs 246.0 MiB
Application code generator... 4/7 [================>-----------]  57% 1 min 266.0 MiB
Interceptors generation... 4/7 [================>-----------]  57% 1 min 266.0 MiB
Interceptors generation... 5/7 [====================>-------]  71% 2 mins 304.0 MiB
Area configuration aggregation... 5/7 [====================>-------]  71% 2 mins 304.0 MiB
                                                               
  [ReflectionException]                                        
  Class Magento\Framework\App\Config\ScopePool does not exist  

		Incompatible argument type: Required type: boolean. Actual type: bool; File: 
/var/www/dalton/magento/vendor/smile/module-elasticsuite-targetrule/Plugin/Indexer/TargetRule/Product/Rule.php

	Smile\ElasticsuiteTargetRule\Model\ResourceModel\Index
		Incompatible argument type: Required type: \Magento\CatalogInventory\Helper\Stock. Actual type: string; File: 
/var/www/dalton/magento/vendor/smile/module-elasticsuite-targetrule/Model/ResourceModel/Index.php

Total Errors Count: 2

**Comment by romainruaud** [comment]
Issue fixed. Please update to the latest release for Magento 2.2
